## BEGIN IGNORE ##

# This section is ignored by the template engine. 
# It is here to stop the ide from reporting errors
# But we don't want to include it as part of the final dockerfile

FROM debia:latest

## END IGNORE ##

ENV PKG /home/${BUNDLE_USER}/{{ PackageID }}.tar.gz

# Make sure that the home directory for nonroot exists
RUN mkdir -p /home/${BUNDLE_USER} && \
	chown -R ${BUNDLE_USER}:${BUNDLE_GID} /home/${BUNDLE_USER}
